name: Main workflow

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.10.1
          - 4.09.1
          - 4.08.1
          - 4.07.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Retrieve opam cache
        uses: actions/cache@v2
        id: cache-opam
        with:
          path: ~/.opam
          key: v1-${{ matrix.os }}-opam-${{ matrix.ocaml-version }}

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      # Check the consistency of installed opam packages
      - run: opam upgrade --fixup
        if: steps.cache-opam.outputs.cache-hit == 'true'

      - run: opam exec -- make

      - run: opam exec -- make test

      - uses: actions/upload-artifact@v2
        with:
          name: unison-${{ github.sha }}-${{ matrix.os }}-${{ matrix.ocaml-version }}
          path: src/unison
